var stateNames = {
  0: "Alabama",
  1: "Alaska",
  2: "Arizona",
  3: "Colorado",
  4: "Florida",
  5: "Georgia",
  6: "Indiana",
  7: "Kansas",
  8: "Maine",
  9: "Massachusetts",
  10: "Minnesota",
  11: "New Jersey",
  12: "North Carolina",
  13: "North Dakota",
  14: "Oklahoma",
  15: "Pennsylvania",
  16: "South Dakota",
  17: "Texas",
  18: "Wyoming",
  19: "Connecticut",
  20: "Missouri",
  21: "West Virginia",
  22: "Illinois",
  23: "New Mexico",
  24: "Arkansas",
  25: "California",
  26: "Delaware",
  28: "Hawaii",
  29: "Iowa",
  30: "Kentucky",
  31: "Maryland",
  32: "Michigan",
  33: "Mississippi",
  34: "Montana",
  35: "New Hampshire",
  36: "New York",
  37: "Ohio",
  38: "Oregon",
  39: "Tennessee",
  40: "Utah",
  41: "Virginia",
  42: "Washington",
  43: "Wisconsin",
  47: "Nebraska",
  48: "South Carolina",
  51: "Idaho",
  52: "Nevada",
  53: "Vermont",
  54: "Lousiana",
  55: "Rhode Island",
};

export { stateNames };
